cmd/devtools/init.go
cmd/devtools/run.go

Previously, the `comtbft init` command was getting run right before starting the Cometbft binary within the `dev run` command.
This was unnecessary, and the initialization of Cometbft has been moved to the `dev init` command.

Relocate Cometbft Initialization

---

internal/ui/app.go
internal/ui/processpane.go
internal/ui/statestore.go
internal/ui/view.go

Move away from UI subcomponents having state and move all state to a state store within the UI app.

Add State Store to App

---

internal/processrunner/processrunner.go
internal/processrunner/processrunner_test.go
internal/safebuffer/safebuffer.go
internal/safebuffer/safebuffer_test.go
internal/testutils/mocks.go
internal/ui/processpane.go
internal/ui/processpane_test.go
internal/ui/view.go
justfile

We were unnecessarily duplicating data between ProcessPane's TextView's buffer and our own SafeBuffer.
Now, the SafeBuffer is reset when data is fetched to be written to TextView's buffer.
I also moved `lineCount` back to ProcessPane. I think it makes sense to have the ui struct keep track of the line count, which is used heavily for the ui functionality.

Feature: add Reset functionality to SafeBuffer so we can keep memory lower

---

.github/workflows/build-for-release.yaml

add -s -w ldflags to build step. we don't need the debugging for the production builds
> -s: This flag omits the symbol table and debug information. The symbol table is used for linking and may also be used by debuggers. Omitting it helps reduce the size of the final binary but may complicate debugging efforts.
> -w: This flag omits the DWARF debugging information. DWARF is a widely used, standardized debugging data format. Omitting this information significantly reduces the size of the binary but, again, makes it more difficult to debug.
closes https://github.com/astriaorg/astria-cli-go/issues/51

Fix: reduce binary size

---

README.md
cmd/devtools/run.go
cmd/logging.go
justfile

Because the TUI manipulates the terminal output, a dedicated log file is required to capture the logs of the app that would normally be written to stdout of stderr.
closes #32

Feature: Add log file for TUI

---

cmd/devtools/binaries_config_darwin_amd64.go
cmd/devtools/binaries_config_darwin_arm64.go
cmd/devtools/binaries_config_linux_amd64.go
cmd/devtools/run.go
cmd/logging.go
internal/processrunner/processrunner.go
internal/processrunner/readychecker.go

Solves the problem of Conductor and Composer starting to quickly after Sequencer starts, causing both of them to crash or hang until they are restarted.
Adds a `ReadyChecker` to the process runner that allows the user to pass a callback function that can perform any required startup checks for a given process.
closes #47

Fix: Wait for Sequencer gRPC server to start before starting other components

---

cmd/devtools/run.go

Both the Sequencer gRPC and CometBFT rpc servers need to be started for Conductor to properly start.
Previously, there was only a check for the Sequncer gRPC.
This pr adds the check for the CometBFT rpc server.
closes #75

Fix: Add CometBFT rpc server ready check

---

cmd/constants.go
cmd/devrunner/config/constants.go
cmd/devrunner/init.go
cmd/devrunner/reset.go
cmd/devrunner/run.go
cmd/sequencer/bridge.go
cmd/sequencer/constants.go
cmd/sequencer/transfer.go

move constant to cmd package. fix typo.
A constant was basically defined in 2 places, which meant it was easy to forget to update both of them if the value changed.

Fix: define constant in single place

---

.github/workflows/project.yaml
cmd/constants.go
cmd/devrunner/config/constants.go
cmd/sequencer/bridge.go
cmd/sequencer/constants.go
cmd/sequencer/transfer.go
integration_tests/cmd_sequencer_integration_test.go
internal/sequencer/sequencer.go
internal/sequencer/types.go

stop gap pr till i can implement full "network config" for sequencer commands

Fix: cli flag and argument fixes for sequencer commands

---

cmd/sequencer/bridge.go
internal/sequencer/sequencer.go
internal/sequencer/types.go

Add Missing Fields to `InitBridgeAccountAction`

---

.github/workflows/build-for-release.yaml

No longer exclude build for linux/arm64

fix: build for linux/arm64

---

.github/workflows/build-for-release.yaml
.github/workflows/nightly-release.yaml

This PR implements a Github action that creates a release at 6AM UTC.
Closes https://github.com/astriaorg/astria-cli-go/issues/113

feature: gh action for nightly releases

---

.github/workflows/build-for-release.yaml
.github/workflows/nightly-release.yaml

must manually build binaries still because build-for-release is not triggered because the nightly release is created via a gh action
for more info: https://github.com/orgs/community/discussions/25281

Fix: add build step to nightly action

---

modules/cli/cmd/devrunner/config/binaries_config_darwin_amd64.go
modules/cli/cmd/devrunner/config/binaries_config_darwin_arm64.go
modules/cli/cmd/devrunner/config/binaries_config_linux_amd64.go
modules/cli/cmd/devrunner/config/networks.go
modules/cli/go.mod
modules/cli/go.sum
modules/cli/internal/sequencer/sequencer.go
modules/go-sequencer-client/README.md
modules/go-sequencer-client/client/client.go

Update cli to use local sequencer client module import.
Add missing sequencer client method `GetBlock`.
Bump services to latest.
related to #120

Fix imports to use local go-sequencer-client module

---

.github/workflows/nightly-release.yaml

I was previously creating a release for each value in the matrix, which would usually fail since you can't create a release that already exists.

Fix: only create single release

---

modules/cli/internal/processrunner/processrunner.go
modules/cli/internal/ui/processpane.go
modules/cli/internal/ui/view.go

When in the main view, you can now minimize or maximize any pane by hitting 'm'.
This does not affect the underlying TextView object that displays the logs. Only the Flex item that holds all the panes are affected and this visual change is reflected only when all the panes on the main view are rendered.

Feature: Add ability to minimize panes on main view

---

.github/workflows/nightly-release.yaml

We are creating a lot of unnecessary builds that add a lot of noise to our releases page.
This PR changes the github action so it only creates a nightly release if there have been changes since the last release.
Closes https://github.com/astriaorg/astria-cli-go/issues/130

chore: only create nightly release if there have been changes

---

modules/cli/README.md
modules/cli/cmd/cliflaghandler.go
modules/cli/cmd/devrunner/config/constants.go
modules/cli/cmd/devrunner/config/tui.go
modules/cli/cmd/devrunner/init.go
modules/cli/cmd/devrunner/run.go
modules/cli/internal/processrunner/processrunner.go
modules/cli/internal/testutils/mocks.go
modules/cli/internal/ui/app.go
modules/cli/internal/ui/processpane.go
modules/cli/internal/ui/statestore.go
modules/cli/internal/ui/view.go

Adds a config file for the TUI app within the cli. This config enables setting values for the following app settings:
- Start with the AutoScroll setting enabled
- Start with word wrap enabled
- Have the fullscreen process panes start in borderless mode
- Set the default instance name
- Choose if the know services (cometbft, sequencer, composer, conductor) start minimized or not
- Choose if all generic services start minimized or not
- Allow override of the default highlight and border color of the process panes for color accessibility
closes #68

Feature: TUI Config

---

modules/cli/cmd/devrunner/purge.go
modules/cli/cmd/devrunner/reset.go

Chore: Update `purge` and `reset` commands descriptions

---

modules/cli/cmd/sequencer/ibctransfer.go
modules/cli/internal/sequencer/helpers.go
modules/cli/internal/sequencer/sequencer.go
modules/cli/internal/sequencer/types.go

Adds IBC transfer as a sequencer command, the command sets a default timeout of 5 minutes for the package sent 
command usage:
`astria-go sequencer ibctransfer [amount] [to] [src-channel] [--keyfile | --keyring-address | --privkey] [flags]`
Tested locally, against dusk-10 & dawn-0

feat: add ibc transfer command

---

.github/workflows/nightly-release.yaml

* get last tag even if current commit has multiple tags
* should only build nightlies if actual changes now

Fix: get proper last tag so nightlies build only when changes detected

---

modules/cli/cmd/devrunner/config/networks.go
modules/cli/cmd/devrunner/config/tui.go
modules/cli/cmd/devrunner/run.go

Allows a user to control if the generic services start before or after the known services.
An additional ready check was added for Composer to make sure all known services are actually up before moving on to the generic services when starting them after. A ready check isn't needed for Conductor.
Also updates env var handling for the Composer to start that service correctly.
closes #172

Feature: Add start order for generic services

---

modules/cli/internal/ui/app.go

Currently the dev-runner allows running without any processes configured, causing a divide by zero panic duo to a [reminder op](https://github.com/astriaorg/astria-cli-go/blob/4dc328596e0e8d441f05f3ae0768114c4f1335bd/modules/cli/internal/ui/view.go#L177). 
- adds a sanity check to the number of processes and gracefully shutdowns the app on failure.

fix(ui): shutdown on empty process panes

---

modules/cli/README.md
modules/cli/cmd/devrunner/config/base.go
modules/cli/cmd/devrunner/config/constants.go
modules/cli/cmd/devrunner/config/helpers.go
modules/cli/cmd/devrunner/config/networks.go
modules/cli/cmd/devrunner/config/tui.go
modules/cli/cmd/devrunner/init.go
modules/cli/cmd/devrunner/reset.go
modules/cli/cmd/devrunner/run.go
modules/cli/cmd/devrunner/setconfig.go
modules/cli/cmd/devrunner/utilities/utilities.go
modules/cli/cmd/helpers.go
modules/cli/cmd/sequencer/config.go
modules/cli/cmd/sequencer/createaccount.go
modules/cli/cmd/sequencer/setconfig.go

This pr adds the ability for the config parsing of the cli to perform shell expansion on the contents.
Previously items like this:
`astria_sequencer_db_filepath = '~/.astria/default/data/astria_sequencer_db'`
Would be parsed literally, causing files to be placed in directories named `~` which can cause issues.
The above will now be properly parsed as though input on the command line.
Similarly, input like the following will also be correctly parsed:
`astria_sequencer_db_filepath = '$HOME/.astria/default/data/astria_sequencer_db'`
closes #175 
closes #178

feat(cli): Add shell expansion to config and flag parsing

---

justfile
modules/cli/cmd/devrunner/config/constants.go
modules/cli/cmd/devrunner/config/tui.go
modules/cli/cmd/devrunner/run.go
modules/cli/internal/processrunner/processrunner.go
modules/cli/internal/testutils/mocks.go
modules/cli/internal/ui/processpane.go

The maximum line limit for the terminal logs displayed within the cli TUI can now me configured using the `max_ui_log_lines` config setting in the `~/.astria/tui-config.toml` file. This allows the TUI to now be used in a long running capacity without worrying about runaway memory usage.
Local testing shows the memory usage of the TUI and all services to be approximately the following (values are rounded up to whole numbers):
- TUI: 22mb
- 1000 lines of logs per service: ~10mb (40mb total)
- Composer: 11mb
- Sequencer: 11mb
- Conductor: 9mb
- CometBFT: 41mb
Total capped memory usage with maxed logs: 134mb
closes #182

feat(cli): configurable max logs lines for tui
